#!/bin/sh -xe

cargo clippy --features=community -- -D warnings
cargo clippy --features=entreprise -- -D warnings

# Check fmt (protip: run 'cargo fmt --all -- --emit files' to apply format locally)
cargo fmt --all -- --check
