name: Build

on:
  push

env:
  CARGO_TERM_COLOR: always
  LIBCLANG_PATH: /usr/lib/llvm-14/lib/

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: [community, enterprise]
    steps:
      - name: Install apt-get
        run: sudo apt-get install -y clang llvm
      - uses: doctolib/actions/checkout@429fae9c3fefa82b9a7fc0223edfaecc7234c787 # checkout-v0.1.0
      - name: Build
        run: cargo build --features=${{ matrix.version }} --verbose
