name: Build

on:
  push

env:
  CARGO_TERM_COLOR: always
  LIBCLANG_PATH: /usr/lib/llvm-14/lib/

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: [community, enterprise]
    steps:
      - name: Install apt-get
        run: sudo apt-get install -y clang llvm
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Build
        run: cargo build --features=${{ matrix.version }} --verbose
