name: Build

on:
  push

env:
  CARGO_TERM_COLOR: always
  LIBCLANG_PATH: /usr/lib/llvm-14/lib/

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: [community, enterprise]
    steps:
      - name: Install apt-get
        run: sudo apt-get install -y clang llvm
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Build
        run: cargo build --features=${{ matrix.version }} --verbose
