name: Clippy check

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [community, enterprise]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends libpcsclite-dev libev-dev libevent-dev libpcsclite-dev pkg-config clang llvm llvm-dev libclang-dev

      - name: Install rust
        uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # v1
        with:
          toolchain: stable
          components: clippy

      - name: Clippy check
        shell: bash
        run: |
          set +e
          # shellcheck disable=SC2046
          cargo clippy --color always --features=${{ matrix.version }}
