name: Clippy check

on: push

env:
  CARGO_TERM_COLOR: always
  LIBCLANG_PATH: /usr/lib/llvm-14/lib/

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [community, enterprise]
    steps:
      - uses: doctolib/actions/checkout@main

      - name: Install rust
        uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: ${{ inputs.target }}

      - run: rustup component add clippy

      - name: Clippy check
        shell: bash
        run: |
          set +e
          # shellcheck disable=SC2046
          cargo clippy --color always --features=${{ matrix.version }}
          exit "${PIPESTATUS[0]}"
