name: Clippy check

on: push

env:
  CARGO_TERM_COLOR: always
  LIBCLANG_PATH: /usr/lib/llvm-14/lib/

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [community, enterprise]
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Clippy
          args: --features=${{ matrix.version }}
