name: Clippy check

on: push

env:
  CARGO_TERM_COLOR: always
  LIBCLANG_PATH: /usr/lib/llvm-14/lib/

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Clippy - community
          args: --features=community
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Clippy - enterprise
          args: --features=enterprise
