name: Rust

on:
  push

env:
  CARGO_TERM_COLOR: always
  LIBCLANG_PATH: /usr/lib/llvm-14/lib/

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install apt-get
      run: sudo apt-get install -y clang llvm
    - name: List libs
      run: ls -l /usr/lib
    - name: Install latest nightly
      uses: dtolnay/rust-toolchain@v1
      with:
          toolchain: nightly
          components: rustfmt, clippy
    - uses: actions/checkout@v3
    - name: Build - community
      run: cargo build --features=community --verbose
    - name: Build - enterprise
      run: cargo build --features=enterprise --verbose
    - name: Run tests - community
      run: cargo test --features=community --verbose
    - name: Run tests - enterprise
      run: cargo test --features=enterprise --verbose
    - name: Run tests (with address sanitizer) - community
      run: LSAN_OPTIONS=suppressions=san.supp RUSTFLAGS="-Zsanitizer=address" cargo +nightly test --features=community --verbose
    - name: Run tests (with address sanitizer) - enterprise
      run: LSAN_OPTIONS=suppressions=san.supp RUSTFLAGS="-Zsanitizer=address" cargo +nightly test --features=enterprise --verbose
